### PR TITLE
refactor the project structure

### PR DESCRIPTION
**Pull request by carlos27g**
As requested, we did the refactor with the following ideas:
- no sub folders in the components 
- views separated from components now
- shared folders
- renamed some jsx files to index

To discuss is:
- the Json files in the About folder ( in views). We do not know where to put them 
- Visualization has inside a src. We did not touch anything here

### CODE REVIEW

**Comment by viganll** [comment]
As part of this pull request I also provided an easy way to import files.
e.g
before: `import Uploader from '../../components/Uploader';`
now: `import Uploader from 'components/Uploader';`

before: `import { filterInProgress, queryJobs } from '../../shared/services/StatusQueueLogic';`
now: `import { filterInProgress, queryJobs } from 'shared/services/StatusQueueLogic';`

**Comment by viganll** [comment]
Resolving all the warnings (when booting the web app) would be a great improvement.

**Review by viganll — APPROVED** [review]
It seems OK from my side. It would be great to remove the warnings as well but I don't think that should be an obstacle for this pull request to be merged.

**Comment by renttrent** [comment]
Lets wait for @gokhansisman to merge new navbar with this branch so we dont have conflicts later. And then its okay to push for me.

**Pull request merged**
