### PR TITLE
Component/modal

### PR DESCRIPTION
**Pull request by renttrent**
### Modal Component

Usage: 
```javascript
// Dashboard.jsx
const Dashboard = () => {
  const [isOpen, setIsOpen] = useState(false)
  return (
    //... 
      <Button onClick={() => setIsOpen(true)}>Open Modal</Button>
      <Modal message="Modal Heading" isOpen={isOpen} onClose={() => setIsOpen(false)}>
        <Box>
          ...
        </Box>
      </Modal>
    //...
  )
}
```

Had some overflow issues when testing on Dashboard index.jsx. Maybe something wrong with dashboard but test it out to be sure.

### CODE REVIEW

**Comment by pal03377** [comment]
How is this different from the built-in [MUI Dialog](https://mui.com/material-ui/react-dialog/)? Could you maybe just use MUI config to modify that instead? That would automatically include potential styling changes in 7 places in the project.

**Comment by renttrent** [comment]
> How is this different from the built-in [MUI Dialog](https://mui.com/material-ui/react-dialog/)? Could you maybe just use MUI config to modify that instead? That would automatically include potential styling changes in 7 places in the project.

@pal03377 I made a custom one that reflects the Figma design. Thanks for the recommendation I might change it to MUI, looks easier.
Btw what do you mean by styling changes in 7 places?

**Comment by renttrent** [comment]
### Modal Update

Updates: 
1. Modal based on MUI Dialog
2. New component: ModalTitle with only some style changes

Modal props: isOpen and children components
ModalTitle props: only children components

Usage:

```javascript
  // Based on MUI docs
  const [open, setOpen] = useState(false)
  
  const descriptionElementRef = useRef(null);
  useEffect(() => {
    if (open) {
      const { current: descriptionElement } = descriptionElementRef;
      if (descriptionElement !== null) {
        descriptionElement.focus();
      }
    }
  }, [open]);

  //...
  <Button
	onClick={ () => setOpen(true) }
  >
	Open
  </Button>
  <Modal isOpen={open}> 
	<ModalTitle>Modal Title</ModalTitle>
	<DialogContent dividers={true}>
	  <DialogContentText
		id="scroll-dialog-description" // dont forget to set this id
		ref={descriptionElementRef}
		tabIndex={-1}
	  >
		{[...new Array(50)].map(
			() => `Cras mattis consectetur purus sit amet fermentum.
			Cras justo odio, dapibus ac facilisis in, egestas eget quam.
			Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
			Praesent commodo cursus magna, vel scelerisque nisl consectetur et.`,
		  )
		  .join('\n')}           
	  </DialogContentText>
	</DialogContent>
	<DialogActions>
	  <Button  variant="outlined" onClick={() => setOpen(false)}>Cancel</Button> //To be replaced with our future buttons
	  <Button onClick={() => setOpen(false)}>Action</Button>
	</DialogActions>
  </Modal>
```

**Comment by pal03377** [comment]
> @pal03377 I made a custom one that reflects the Figma design. Thanks for the recommendation I might change it to MUI, looks easier. Btw what do you mean by styling changes in 7 places?

@renttrent There are 7 files in the project where the MUI `<Dialog>` component is used already, so I thought it would be nice to just directly adapt its styling. But now most of the code will be reusable with this anyways, so it's good 👍

**Pull request merged**
